### ISSUE TITLE
feature (or documentation) checklist

### ISSUE THREAD

**Issue by kozo2** [domitry/mikon#4]
my feature or documentation requests (or checklist)
the method names are taken from

## pandas

- [ ] groupby
- [ ] sum, mean, cov, corr, rank
- [ ] shape
- [ ] describe
- [ ] isnull, notnull, fillna

## statsmodels

- [ ] get_rdataset

**Comment by v0dro** [comment]
[daru](https://github.com/v0dro/daru/)  now supports all this and more. Do give it a shot!

**Comment by kozo2** [comment]
@v0dro Thanks! I try daru!
